name = "ravenscar_full_rp2040"
description = "Ravenscar Full run-time for the RP2040"
version = "0.2.0"

authors = ["AdaCore", "Jeremy Grosser", "Fabien Chouteau", "Daniel King"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]

project-files = ["ravenscar_build.gpr"]

[[depends-on]]
gnat_arm_elf = "^12"
rp2040_hal = "^2.0.1"

[configuration.values]
rp2040_hal.Interrupts = "bb_runtimes"
rp2040_hal.Use_Startup = false

[[pins]]
rp2040_hal = { url='https://github.com/JeremyGrosser/rp2040_hal' }
